# Generated by Django 3.2.4 on 2021-06-10 11:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contactbook_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='person',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='contactbook_app.person'),
        ),
    ]
